<?php
namespace Simpleblog\Model;
use Simpleblog\Classes\Logger;

class Article extends Model
{
	/**
	 * name of database table used by Article
	 * 
	 * @var string
	 */
	protected static $table = 'articles';

	/**
	 * article title
	 * 
	 * @var string
	 */
	public $title;

	/**
	 * main content for article - used when a single article is displayed
	 * 
	 * @var string
	 */
	public $content;

	/**
	 * short preview of content - used when all articles are displayed
	 * 
	 * @var string
	 */
	public $contentPreview;

	/**
	 * date the article was created - auto generated by MySQL
	 * 
	 * @var string
	 */
	public $date;

	/**
	 * create a new Article instance based on array data
	 * 
	 * @param PDO   $connection
	 * @param array $data 
	 */
	public function __construct(\PDO $connection, array $data)
	{
		parent::__construct($connection, $data);

		$this->title = $data['title'];
		$this->content = $data['content'];
		$this->contentPreview = $data['content_preview'];
		$this->date = $data['date'];
	}

	/**
	 * insert a new Article instance into the database
	 * 
	 * @return true|false indicates whether Article was successfully inserted
	 *
	 * @throws Exception if Article fails to insert - routes to errorController
	 */
	public function insert()
	{
		try {
			$query = $this->connection->prepare("INSERT INTO ".self::$table."(title, content, content_preview) VALUES (:title, :content, :contentPreview)");
			$query->bindParam(':title', $this->title);
			$query->bindParam(':content', $this->content);
			$query->bindParam(':contentPreview', $this->contentPreview);
			$query->execute();

			$this->id = $this->connection->lastInsertId();

			return true;
		} catch (\PDOException $e) {
			Logger::log($e->getMessage());
			Throw new \Exception('databaseError');
			return false;
		}
	}

	/**
	 * updates info for an Article that already exsists in the database
	 * 
	 * @return PDOStatement|false indicates whether Article was successfully updated
	 *
	 * @throws Exception if Article fails to update - routes to errorController
	 */
	public function update()
	{
		try {
			$query = $this->connection->prepare("UPDATE ".self::$table." SET title=:title, content=:content, content_preview=:contentPreview WHERE id=:id");
			$query->bindParam(':title', $this->title);
			$query->bindParam(':content', $this->content);
			$query->bindParam(':contentPreview', $this->contentPreview);
			$query->bindParam(':id', $this->id);

			return $query->execute();
		} catch (\PDOException $e) {
			Logger::log($e->getMessage());
			Throw new \Exception('databaseError');
			return false;
		}
	}

}